import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import Providers from "../providers/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className="antialiased flex flex-col min-h-screen"
      >
        <Providers>
          <header>
            <Navbar />
          </header>
          {/* Offset fixed navbar height (daisyUI navbar is ~4rem). */}
          <main className="grow pt-16">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
